# Generated by Django 4.1.7 on 2023-05-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(db_column="place", max_length=50)),
                ("parking", models.CharField(db_column="parking", max_length=50)),
                (
                    "parking_lot",
                    models.CharField(db_column="parking_lot", max_length=50),
                ),
                ("rating", models.CharField(db_column="rating", max_length=50)),
            ],
            options={
                "db_table": "restaurant",
            },
        ),
        migrations.CreateModel(
            name="tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(db_column="place", max_length=50)),
                ("parking", models.CharField(db_column="parking", max_length=50)),
                (
                    "parking_lot",
                    models.CharField(db_column="parking_lot", max_length=50),
                ),
                ("rating", models.CharField(db_column="rating", max_length=50)),
            ],
            options={
                "db_table": "tour",
            },
        ),
    ]
