# Generated by Django 4.1.7 on 2023-05-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_column='user_id', max_length=50)),
                ('passwd', models.CharField(db_column='passwd', max_length=50)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('email', models.CharField(db_column='email', max_length=50)),
                ('mbti', models.CharField(db_column='mbti', max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
