# Generated by Django 4.1.7 on 2023-06-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='rating',
            field=models.CharField(db_column='rating', default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='stamp',
            field=models.IntegerField(db_column='stamp', default=0),
        ),
    ]
