# Generated by Django 4.1.7 on 2023-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_marker"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="rating",
            field=models.CharField(db_column="rating", default=2, max_length=50),
            preserve_default=False,
        ),
    ]
